apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-a-level-1-deployment
  namespace: plan-a-level-1-namespace
  labels:
    app: plan-a-level-1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plan-a-level-1-app
  template:
    metadata:
      labels:
        app: plan-a-level-1-app
    spec: 
      containers:
      - name: plan-a-demo
        image: gonzape27/plan-a-level-1-app:latest
        ports:
        - containerPort: 3000
